title: monia
author: Keallar
email: zlysanskiy@gmail.com
tagline: "A jekyll theme that use iA Writer Mono font and shell view"
description: "This is a preview of Monia"
github_username: Keallar
baseurl: '/jekyll-monia'
url: 'https://keallar.github.io'

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jemoji

sass:
  style: compressed

# highlight code
highlighter: rouge

# pagination
paginate: 1
paginate_path: "/blog/page:num/"

header_pages:
  - read-me.md
  - preview.md
