title: monia
author: Keallar
email: zlysanskiy@gmail.com
tagline: "A jekyll theme that use iA Writer Mono font and shell view"
description: "This is a preview of Monia"
github_username: Keallar

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
  - jekyll-paginate

sass:
  style: compressed

theme: jekyll-monia

# highlight code
highlighter: rouge

# pagination
paginate: 2
paginate_path: "/blog/page:num/"

header_pages:
  - read-me.md
  - preview.md
