title: jekyll-monia
author: Keallar
email: zlysanskiy@gmail.com
tagline: "A jekyll theme that use iA Writer Mono font and shell view"
description: "This is a preview of Monia"
baseurl: '/jekyll-monia'
url: 'https://keallar.github.io'

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

sass:
  style: compressed


# highlight code
highlighter: rouge

# pagination
paginate: 1
paginate_path: "/blog/page:num/"

header_pages:
  - read-me.md
  - preview.md

social_links:
  - url: https://twitter.com/EugeneLys
    icon: twitter-square
  - url: https://github.com/Keallar
    icon: github-square